version: 0.1

phases:
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
      - cd app && npm install
      - echo "dependencies install completed `date`"
      - echo "vulnerabilities check"
      - ./node_modules/.bin/nsp check .
  build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file app-output_sam.yaml
artifacts:
  type: zip
  files:
    - app-output_sam.yaml
    - 'dev-configuration.json'
  discard-paths: yes
